[cookie]
Timeout = 600
CookieName = "siebelMaintenceSession"

[server]
HttpPort = 9090
HttpsPort = 9091
CertName = "D:\\Dev\\GoLang\\src\\GoWeb\\Siebel\\cert.pem"
KeyName = "D:\\Dev\\GoLang\\src\\GoWeb\\Siebel\\key.pem"

[activeDirectory]
Base = "DC=Olympus,DC=F5Net,DC=com"
Host = "ad-ldap.olympus.f5net.com"
Port = 389
UseSSL = false
BindUser = "_StgSiebelADSIUser"
BindPassword = "xxxx"

[siebel]
ServiceRequestPath = "D:\\Dev\\projects-data\\data\\siebel\\messages\\in\\"
